```typescript
import React, { useContext, useState, useEffect, useMemo, useCallback } from 'react';
import { DataContext } from '../context/DataContext';
import Card from './Card';
import { GoogleGenAI } from '@google/genai';
import { AlertTriangle, Zap, TrendingUp, ShieldCheck, Cpu, BarChart3, RefreshCw, Loader2, Settings, History, BrainCircuit, Bot, SlidersHorizontal, Banknote, Link as LinkIcon, FileCode2, FlaskConical, Lightbulb, PiggyBank, FileText, Calendar, Clock, User, Users, Home, Building, MapPin, Phone, Mail, Twitter, Facebook, Instagram, Globe, Search, Plus, Minus, Check, X, ChevronDown, ChevronUp, ExternalLink } from 'lucide-react';

// The James Burvel O'Callaghan III Code - CreditHealthView.tsx - Version 1.0

// --- A. Constants for Enhanced UI/UX and Data Integrity ---
const A1_SCORE_RATING_MAP = {
    'Excellent': { color: 'text-green-400', border: 'border-green-500', icon: ShieldCheck, glow: 'shadow-[0_0_20px_rgba(74,222,128,0.5)]' },
    'Good': { color: 'text-blue-400', border: 'border-blue-500', icon: TrendingUp, glow: 'shadow-[0_0_20px_rgba(59,130,246,0.5)]' },
    'Fair': { color: 'text-yellow-400', border: 'border-yellow-500', icon: AlertTriangle, glow: 'shadow-[0_0_20px_rgba(250,204,21,0.5)]' },
    'Poor': { color: 'text-red-400', border: 'border-red-500', icon: AlertTriangle, glow: 'shadow-[0_0_20px_rgba(239,68,68,0.5)]' },
};

const A2_FACTOR_STATUS_STYLES = {
    'Excellent': { indicator: 'bg-green-500', text: 'text-green-300' },
    'Good': { indicator: 'bg-blue-500', text: 'text-blue-300' },
    'Fair': { indicator: 'bg-yellow-500', text: 'text-yellow-300' },
    'Poor': { indicator: 'bg-red-500', text: 'text-red-300' },
};

const A3_COMPANY_COLORS = ['bg-red-100', 'bg-green-100', 'bg-blue-100', 'bg-yellow-100', 'bg-purple-100', 'bg-pink-100', 'bg-gray-100', 'bg-indigo-100', 'bg-teal-100', 'bg-orange-100'];

const A4_USE_CASES = [
    { id: 'uc001', name: 'Apply for a Mortgage', description: 'Obtain a loan to purchase a home.', companyId: 'c001' },
    { id: 'uc002', name: 'Rent an Apartment', description: 'Secure housing by leasing a property.', companyId: 'c002' },
    { id: 'uc003', name: 'Lease a Car', description: 'Obtain a vehicle through a leasing agreement.', companyId: 'c003' },
    { id: 'uc004', name: 'Open a Bank Account', description: 'Establish a new account for financial transactions.', companyId: 'c004' },
    { id: 'uc005', name: 'Get a Credit Card', description: 'Apply for a new credit card.', companyId: 'c005' },
    { id: 'uc006', name: 'Start a Business', description: 'Obtain funding for a new business venture.', companyId: 'c006' },
    { id: 'uc007', name: 'Invest in Stocks', description: 'Open a brokerage account and invest in the stock market.', companyId: 'c007' },
    { id: 'uc008', name: 'Secure a Personal Loan', description: 'Borrow funds for personal expenses.', companyId: 'c008' },
    { id: 'uc009', name: 'Finance Education', description: 'Obtain loans for educational expenses.', companyId: 'c009' },
    { id: 'uc010', name: 'Insurance Coverage', description: 'Get Insured against unforeseen liabilities.', companyId: 'c010' },
    { id: 'uc011', name: 'Peer-to-Peer Lending', description: 'Borrow from and lend to your peers.', companyId: 'c011' },
    { id: 'uc012', name: 'Invoice Factoring', description: 'Get your invoices cleared instantly.', companyId: 'c012' },
    { id: 'uc013', name: 'Equipment Financing', description: 'Get financing for equipment purchases.', companyId: 'c013' },
    { id: 'uc014', name: 'Supply Chain Financing', description: 'Secure funding for supply chain operations.', companyId: 'c014' },
    { id: 'uc015', name: 'Import/Export Financing', description: 'Secure funding for import/export activities.', companyId: 'c015' },
    { id: 'uc016', name: 'Franchise Financing', description: 'Secure funding for franchise operations.', companyId: 'c016' },
    { id: 'uc017', name: 'Crowdfunding', description: 'Get public funding for a project.', companyId: 'c017' },
    { id: 'uc018', name: 'Venture Capital', description: 'Get funding from a venture capitalist.', companyId: 'c018' },
    { id: 'uc019', name: 'Angel Investment', description: 'Secure funding from an angel investor.', companyId: 'c019' },
    { id: 'uc020', name: 'Government Grants', description: 'Get funding from government grants.', companyId: 'c020' },
    { id: 'uc021', name: 'Small Business Loans', description: 'Secure loans from small businesses.', companyId: 'c021' },
    { id: 'uc022', name: 'Line of Credit', description: 'Open a line of credit.', companyId: 'c022' },
    { id: 'uc023', name: 'Merchant Cash Advance', description: 'Get an advance on your merchant cash.', companyId: 'c023' },
    { id: 'uc024', name: 'Buy Now, Pay Later', description: 'Make Purchases with no upfront money.', companyId: 'c024' },
    { id: 'uc025', name: 'Payday Loans', description: 'Instant loans for short time horizons.', companyId: 'c025' },
    { id: 'uc026', name: 'Title Loans', description: 'Loans secured by the title of your car.', companyId: 'c026' },
    { id: 'uc027', name: 'Pawn Shop Loans', description: 'Loans secured by collateral.', companyId: 'c027' },
    { id: 'uc028', name: 'Overdraft Protection', description: 'Automatic coverage for potential overdrafts.', companyId: 'c028' },
    { id: 'uc029', name: 'Bill Consolidation', description: 'Combine multiple bills into a single payment.', companyId: 'c029' },
    { id: 'uc030', name: 'Debt Management Plan', description: 'Establish a plan to manage and reduce debt.', companyId: 'c030' },
    { id: 'uc031', name: 'Debt Settlement', description: 'Negotiate to reduce outstanding debt.', companyId: 'c031' },
    { id: 'uc032', name: 'Bankruptcy', description: 'Declare bankruptcy.', companyId: 'c032' },
    { id: 'uc033', name: 'Credit Counseling', description: 'Seek assistance from a credit counselor.', companyId: 'c033' },
    { id: 'uc034', name: 'Financial Planning', description: 'Get financial advice to optimize financial standing.', companyId: 'c034' },
    { id: 'uc035', name: 'Retirement Planning', description: 'Get retirement advice to optimize financial standing.', companyId: 'c035' },
    { id: 'uc036', name: 'Estate Planning', description: 'Plan your estate for future generations.', companyId: 'c036' },
    { id: 'uc037', name: 'Tax Planning', description: 'Plan your taxes to optimize financial standings.', companyId: 'c037' },
    { id: 'uc038', name: 'College Savings Plan', description: 'Plan your child\'s college fees to optimize financial standings.', companyId: 'c038' },
    { id: 'uc039', name: 'Savings Accounts', description: 'Open a new savings account.', companyId: 'c039' },
    { id: 'uc040', name: 'Money Market Accounts', description: 'Open a new money market account.', companyId: 'c040' },
    { id: 'uc041', name: 'Certificates of Deposit', description: 'Open a certificate of deposit.', companyId: 'c041' },
    { id: 'uc042', name: 'Bonds', description: 'Invest in bonds.', companyId: 'c042' },
    { id: 'uc043', name: 'Mutual Funds', description: 'Invest in mutual funds.', companyId: 'c043' },
    { id: 'uc044', name: 'Exchange-Traded Funds', description: 'Invest in exchange-traded funds.', companyId: 'c044' },
    { id: 'uc045', name: 'Real Estate Investment', description: 'Invest in real estate.', companyId: 'c045' },
    { id: 'uc046', name: 'Cryptocurrency Investment', description: 'Invest in cryptocurrency.', companyId: 'c046' },
    { id: 'uc047', name: 'Commodity Investment', description: 'Invest in commodities.', companyId: 'c047' },
    { id: 'uc048', name: 'Annuities', description: 'Invest in annuities.', companyId: 'c048' },
    { id: 'uc049', name: 'Life Insurance', description: 'Get life insurance.', companyId: 'c049' },
    { id: 'uc050', name: 'Health Insurance', description: 'Get health insurance.', companyId: 'c050' },
    { id: 'uc051', name: 'Disability Insurance', description: 'Get disability insurance.', companyId: 'c051' },
    { id: 'uc052', name: 'Long-Term Care Insurance', description: 'Get long-term care insurance.', companyId: 'c052' },
    { id: 'uc053', name: 'Homeowners Insurance', description: 'Get homeowners insurance.', companyId: 'c053' },
    { id: 'uc054', name: 'Car Insurance', description: 'Get car insurance.', companyId: 'c054' },
    { id: 'uc055', name: 'Renters Insurance', description: 'Get renters insurance.', companyId: 'c055' },
    { id: 'uc056', name: 'Umbrella Insurance', description: 'Get umbrella insurance.', companyId: 'c056' },
    { id: 'uc057', name: 'Travel Insurance', description: 'Get travel insurance.', companyId: 'c057' },
    { id: 'uc058', name: 'Pet Insurance', description: 'Get pet insurance.', companyId: 'c058' },
    { id: 'uc059', name: 'Identity Theft Insurance', description: 'Get identity theft insurance.', companyId: 'c059' },
    { id: 'uc060', name: 'Cyber Insurance', description: 'Get cyber insurance.', companyId: 'c060' },
    { id: 'uc061', name: 'Buy a Car', description: 'Purchase a car.', companyId: 'c061' },
    { id: 'uc062', name: 'Buy a House', description: 'Purchase a house.', companyId: 'c062' },
    { id: 'uc063', name: 'Buy a Boat', description: 'Purchase a boat.', companyId: 'c063' },
    { id: 'uc064', name: 'Buy a Plane', description: 'Purchase a plane.', companyId: 'c064' },
    { id: 'uc065', name: 'Buy a Motorcycle', description: 'Purchase a motorcycle.', companyId: 'c065' },
    { id: 'uc066', name: 'Start a Family', description: 'Plan for the financial implications of starting a family.', companyId: 'c066' },
    { id: 'uc067', name: 'Send Money to Family Overseas', description: 'Send money to family living overseas.', companyId: 'c067' },
    { id: 'uc068', name: 'Home Improvement', description: 'Finance home improvement projects.', companyId: 'c068' },
    { id: 'uc069', name: 'Travel & Leisure', description: 'Obtain credit for travel and leisure activities.', companyId: 'c069' },
    { id: 'uc070', name: 'Medical Expenses', description: 'Cover unforeseen medical expenses.', companyId: 'c070' },
    { id: 'uc071', name: 'Dental Care', description: 'Cover dental care expenses.', companyId: 'c071' },
    { id: 'uc072', name: 'Vision Care', description: 'Cover vision care expenses.', companyId: 'c072' },
    { id: 'uc073', name: 'Cosmetic Procedures', description: 'Finance cosmetic procedures.', companyId: 'c073' },
    { id: 'uc074', name: 'Legal Fees', description: 'Finance legal fees.', companyId: 'c074' },
    { id: 'uc075', name: 'Moving Expenses', description: 'Finance moving expenses.', companyId: 'c075' },
    { id: 'uc076', name: 'Wedding Expenses', description: 'Finance wedding expenses.', companyId: 'c076' },
    { id: 'uc077', name: 'Funeral Expenses', description: 'Finance funeral expenses.', companyId: 'c077' },
    { id: 'uc078', name: 'Emergency Fund', description: 'Establish an emergency fund.', companyId: 'c078' },
    { id: 'uc079', name: 'Vacation Planning', description: 'Plan and budget for vacations.', companyId: 'c079' },
    { id: 'uc080', name: 'Gifting', description: 'Budget for and manage gifts.', companyId: 'c080' },
    { id: 'uc081', name: 'Charitable Giving', description: 'Plan and manage charitable donations.', companyId: 'c081' },
    { id: 'uc082', name: 'Club Memberships', description: 'Finance club memberships.', companyId: 'c082' },
    { id: 'uc083', name: 'Subscription Services', description: 'Manage subscriptions and recurring payments.', companyId: 'c083' },
    { id: 'uc084', name: 'Online Courses & Education', description: 'Finance online courses and further education.', companyId: 'c084' },
    { id: 'uc085', name: 'Digital Assets', description: 'Purchase digital assets.', companyId: 'c085' },
    { id: 'uc086', name: 'Intellectual Property', description: 'Finance intellectual property.', companyId: 'c086' },
    { id: 'uc087', name: 'Patent Filing', description: 'Finance patent filing.', companyId: 'c087' },
    { id: 'uc088', name: 'Trademark Registration', description: 'Finance trademark registration.', companyId: 'c088' },
    { id: 'uc089', name: 'Copyright Protection', description: 'Finance copyright protection.', companyId: 'c089' },
    { id: 'uc090', name: 'Debt Refinancing', description: 'Refinance existing debt.', companyId: 'c090' },
    { id: 'uc091', name: 'Budgeting', description: 'Create and stick to a budget.', companyId: 'c091' },
    { id: 'uc092', name: 'Financial Literacy', description: 'Improve your financial literacy.', companyId: 'c092' },
    { id: 'uc093', name: 'Credit Monitoring', description: 'Monitor your credit score and report.', companyId: 'c093' },
    { id: 'uc094', name: 'Fraud Protection', description: 'Protect yourself from fraud and identity theft.', companyId: 'c094' },
    { id: 'uc095', name: 'Will Preparation', description: 'Prepare a will.', companyId: 'c095' },
    { id: 'uc096', name: 'Power of Attorney', description: 'Get power of attorney.', companyId: 'c096' },
    { id: 'uc097', name: 'Healthcare Proxy', description: 'Establish a healthcare proxy.', companyId: 'c097' },
    { id: 'uc098', name: 'Living Will', description: 'Prepare a living will.', companyId: 'c098' },
    { id: 'uc099', name: 'Tax Preparation', description: 'Prepare your taxes.', companyId: 'c099' },
    { id: 'uc100', name: 'Financial Coaching', description: 'Receive personalized financial coaching.', companyId: 'c100' },
];

const A5_COMPANIES = [
    { id: 'c001', name: 'Burvel Mortgage Inc.', description: 'Mortgage lending services.', industry: 'Finance', logo: 'B', colorIndex: 0, website: 'https://burvelmortgage.com' },
    { id: 'c002', name: 'O\'Callaghan Rentals', description: 'Apartment rental management.', industry: 'Real Estate', logo: 'O', colorIndex: 1, website: 'https://ocallaghanrentals.com' },
    { id: 'c003', name: 'James Automotive Leasing', description: 'Car leasing services.', industry: 'Automotive', logo: 'J', colorIndex: 2, website: 'https://jamesautoleasing.com' },
    { id: 'c004', name: 'Burvel Banking Corp.', description: 'Retail banking services.', industry: 'Finance', logo: 'B', colorIndex: 3, website: 'https://burvelbanking.com' },
    { id: 'c005', name: 'O\'Callaghan Credit Union', description: 'Credit card services.', industry: 'Finance', logo: 'O', colorIndex: 4, website: 'https://ocallaghancreditunion.com' },
    { id: 'c006', name: 'James Capital Ventures', description: 'Venture capital for startups.', industry: 'Finance', logo: 'J', colorIndex: 5, website: 'https://jamescapitalventures.com' },
    { id: 'c007', name: 'Burvel Investments LLC', description: 'Stock market investment services.', industry: 'Finance', logo: 'B', colorIndex: 6, website: 'https://burvelinvestments.com' },
    { id: 'c008', name: 'O\'Callaghan Personal Loans', description: 'Personal loan services.', industry: 'Finance', logo: 'O', colorIndex: 7, website: 'https://ocallaghanpersonalloans.com' },
    { id: 'c009', name: 'James Education Finance', description: 'Education loan services.', industry: 'Finance', logo: 'J', colorIndex: 8, website: 'https://jameseducationfinance.com' },
    { id: 'c010', name: 'Burvel Insurance Group', description: 'Insurance coverage services.', industry: 'Insurance', logo: 'B', colorIndex: 9, website: 'https://burvelinsurance.com' },
    { id: 'c011', name: 'O\'Callaghan Lending', description: 'Peer-to-peer lending services.', industry: 'Finance', logo: 'O', colorIndex: 0, website: 'https://ocallaghanlending.com' },
    { id: 'c012', name: 'James Factoring', description: 'Invoice factoring services.', industry: 'Finance', logo: 'J', colorIndex: 1, website: 'https://jamesfactoring.com' },
    { id: 'c013', name: 'Burvel Equipment Financing', description: 'Equipment financing services.', industry: 'Finance', logo: 'B', colorIndex: 2, website: 'https://burvelequipmentfinancing.com' },
    { id: 'c014', name: 'O\'Callaghan Supply Chain Finance', description: 'Supply chain financing services.', industry: 'Finance', logo: 'O', colorIndex: 3, website: 'https://ocallaghansupplychain.com' },
    { id: 'c015', name: 'James Import Export Finance', description: 'Import/export financing services.', industry: 'Finance', logo: 'J', colorIndex: 4, website: 'https://jamesimportexportfinance.com' },
    { id: 'c016', name: 'Burvel Franchise Finance', description: 'Franchise financing services.', industry: 'Finance', logo: 'B', colorIndex: 5, website: 'https://burvelfranchisefinance.com' },
    { id: 'c017', name: 'O\'Callaghan Crowdfunding', description: 'Crowdfunding platform.', industry: 'Finance', logo: 'O', colorIndex: 6, website: 'https://ocallaghancrowdfunding.com' },
    { id: 'c018', name: 'James Venture Capital', description: 'Venture capital investments.', industry: 'Finance', logo: 'J', colorIndex: 7, website: 'https://jamesventurecapital.com' },
    { id: 'c019', name: 'Burvel Angel Investors', description: 'Angel investment network.', industry: 'Finance', logo: 'B', colorIndex: 8, website: 'https://burvelangelinvestors.com' },
    { id: 'c020', name: 'O\'Callaghan Grants', description: 'Government grant assistance.', industry: 'Government', logo: 'O', colorIndex: 9, website: 'https://ocallaghangrants.com' },
    { id: 'c021', name: 'James Small Business Loans', description: 'Small business loan services.', industry: 'Finance', logo: 'J', colorIndex: 0, website: 'https://jamessmallbusinessloans.com' },
    { id: 'c022', name: 'Burvel Line of Credit', description: 'Line of credit services.', industry: 'Finance', logo: 'B', colorIndex: 1, website: 'https://burvellineofcredit.com' },
    { id: 'c023', name: 'O\'Callaghan Merchant Advance', description: 'Merchant cash advance services.', industry: 'Finance', logo: 'O', colorIndex: 2, website: 'https://ocallaghanmerchantadvance.com' },
    { id: 'c024', name: 'James Buy Now Pay Later', description: 'Buy now, pay later financing.', industry: 'Finance', logo: 'J', colorIndex: 3, website: 'https://jamesbuynowpaylater.com' },
    { id: 'c025', name: 'Burvel Payday Loans', description: 'Payday loan services.', industry: 'Finance', logo: 'B', colorIndex: 4, website: 'https://burvelpaydayloans.com' },
    { id: 'c026', name: 'O\'Callaghan Title Loans', description: 'Title loan services.', industry: 'Finance', logo: 'O', colorIndex: 5, website: 'https://ocallaghantitleloans.com' },
    { id: 'c027', name: 'James Pawn Shop Loans', description: 'Pawn shop loan services.', industry: 'Finance', logo: 'J', colorIndex: 6, website: 'https://jamespawnshoploans.com' },
    { id: 'c028', name: 'Burvel Overdraft Protection', description: 'Overdraft protection services.', industry: 'Finance', logo: 'B', colorIndex: 7, website: 'https://burveloverdraftprotection.com' },
    { id: 'c029', name: 'O\'Callaghan Bill Consolidation', description: 'Bill consolidation services.', industry: 'Finance', logo: 'O', colorIndex: 8, website: 'https://ocallaghanbillconsolidation.com' },
    { id: 'c030', name: 'James Debt Management', description: 'Debt management plan services.', industry: 'Finance', logo: 'J', colorIndex: 9, website: 'https://jamesdebtmanagement.com' },
    { id: 'c031', name: 'Burvel Debt Settlement', description: 'Debt settlement services.', industry: 'Finance', logo: 'B', colorIndex: 0, website: 'https://burveldebtsettlement.com' },
    { id: 'c032', name: 'O\'Callaghan Bankruptcy Assistance', description: 'Bankruptcy assistance services.', industry: 'Legal', logo: 'O', colorIndex: 1, website: 'https://ocallaghanbankruptcy.com' },
    { id: 'c033', name: 'James Credit Counseling', description: 'Credit counseling services.', industry: 'Finance', logo: 'J', colorIndex: 2, website: 'https://jamescreditcounseling.com' },
    { id: 'c034', name: 'Burvel Financial Planning', description: 'Financial planning services.', industry: 'Finance', logo: 'B', colorIndex: 3, website: 'https://burvelfinancialplanning.com' },
    { id: 'c035', name: 'O\'Callaghan Retirement Planning', description: 'Retirement planning services.', industry: 'Finance', logo: 'O', colorIndex: 4, website: 'https://ocallaghanretirement.com' },
    { id: 'c036', name: 'James Estate Planning', description: 'Estate planning services.', industry: 'Legal', logo: 'J', colorIndex: 5, website: 'https://jamesestateplanning.com' },
    { id: 'c037', name: 'Burvel Tax Planning', description: 'Tax planning services.', industry: 'Finance', logo: 'B', colorIndex: 6, website: 'https://burveltaxplanning.com' },
    { id: 'c038', name: 'O\'Callaghan College Savings', description: 'College savings plans.', industry: 'Finance', logo: 'O', colorIndex: 7, website: 'https://ocallaghancollegesavings.com' },
    { id: 'c039', name: 'James Savings Accounts', description: 'Savings account services.', industry: 'Finance', logo: 'J', colorIndex: 8, website: 'https://jamessavingsaccounts.com' },
    { id: 'c040', name: 'Burvel Money Market', description: 'Money market account services.', industry: 'Finance', logo: 'B', colorIndex: 9, website: 'https://burvelmoneymarket.com' },
    { id: 'c041', name: 'O\'Callaghan Certificates', description: 'Certificates of deposit services.', industry: 'Finance', logo: 'O', colorIndex: 0, website: 'https://ocallaghancertificates.com' },
    { id: 'c042', name: 'James Bonds Investments', description: 'Bond investment services.', industry: 'Finance', logo: 'J', colorIndex: 1, website: 'https://jamesbondsinvestments.com' },
    { id: 'c043', name: 'Burvel Mutual Funds', description: 'Mutual fund investment services.', industry: 'Finance', logo: 'B', colorIndex: 2, website: 'https://burvelmutualfunds.com' },
    { id: 'c044', name: 'O\'Callaghan ETFs', description: 'ETF investment services.', industry: 'Finance', logo: 'O', colorIndex: 3, website: 'https://ocallaghanetfs.com' },
    { id: 'c045', name: 'James Real Estate', description: 'Real estate investment services.', industry: 'Real Estate', logo: 'J', colorIndex: 4, website: 'https://jamesrealestateinvestments.com' },
    { id: 'c046', name: 'Burvel Crypto Investments', description: 'Cryptocurrency investment services.', industry: 'Finance', logo: 'B', colorIndex: 5, website: 'https://burvelcryptoinvestments.com' },
    { id: 'c047', name: 'O\'Callaghan Commodities', description: 'Commodity investment services.', industry: 'Finance', logo: 'O', colorIndex: 6, website: 'https://ocallaghancommodities.com' },
    { id: 'c048', name: 'James Annuities', description: 'Annuity investment services.', industry: 'Finance', logo: 'J', colorIndex: 7, website: 'https://jamesannuities.com' },
    { id: 'c049', name: 'Burvel Life Insurance', description: 'Life insurance services.', industry: 'Insurance', logo: 'B', colorIndex: 8, website: 'https://burvellifeinsurance.com' },
    { id: 'c050', name: 'O\'Callaghan Health Insurance', description: 'Health insurance services.', industry: 'Insurance', logo: 'O', colorIndex: 9, website: 'https://ocallaghanhealthinsurance.com' },
    { id: 'c051', name: 'James Disability Insurance', description: 'Disability insurance services.', industry: 'Insurance', logo: 'J', colorIndex: 0, website: 'https://jamesdisabilityinsurance.com' },
    { id: 'c052', name: 'Burvel Long Term Care', description: 'Long-term care insurance services.', industry: 'Insurance', logo: 'B', colorIndex: 1, website: 'https://burvellongtermcare.com' },
    { id: 'c053', name: 'O\'Callaghan Home Insurance', description: 'Homeowners insurance services.', industry: 'Insurance', logo: 'O', colorIndex: 2, website: 'https://ocallaghanhomeinsurance.com' },
    { id: 'c054', name: 'James Car Insurance', description: 'Car insurance services.', industry: 'Insurance', logo: 'J', colorIndex: 3, website: 'https://jamescarinsurance.com' },
    { id: 'c055', name: 'Burvel Renters Insurance', description: 'Renters insurance services.', industry: 'Insurance', logo: 'B', colorIndex: 4, website: 'https://burvelrentersinsurance.com' },
    { id: 'c056', name: 'O\'Callaghan Umbrella Insurance', description: 'Umbrella insurance services.', industry: 'Insurance', logo: 'O', colorIndex: 5, website: 'https://ocallaghanumbrellainsurance.com' },
    { id: 'c057', name: 'James Travel Insurance', description: 'Travel insurance services.', industry: 'Insurance', logo: 'J', colorIndex: 6, website: 'https://jamestravelinsurance.com' },
    { id: 'c058', name: 'Burvel Pet Insurance', description: 'Pet insurance services.', industry: 'Insurance', logo: 'B', colorIndex: 7, website: 'https://burvelpetinsurance.com' },
    { id: 'c059', name: 'O\'Callaghan Identity Theft', description: 'Identity theft insurance services.', industry: 'Insurance', logo: 'O', colorIndex: 8, website: 'https://ocallaghanidentitytheft.com' },
    { id: 'c060', name: 'James Cyber Insurance', description: 'Cyber insurance services.', industry: 'Insurance', logo: 'J', colorIndex: 9, website: 'https://jamescyberinsurance.com' },
    { id: 'c061', name: 'Burvel Auto Sales', description: 'Car sales services.', industry: 'Automotive', logo: 'B', colorIndex: 0, website: 'https://burvelautosales.com' },
    { id: 'c062', name: 'O\'Callaghan Realty', description: 'Real estate sales services.', industry: 'Real Estate', logo: 'O', colorIndex: 1, website: 'https://ocallaghanrealty.com' },
    { id: 'c063', name: 'James Boat Sales', description: 'Boat sales services.', industry: 'Marine', logo: 'J', colorIndex: 2, website: 'https://jamesboatsales.com' },
    { id: 'c064', name: 'Burvel Aviation', description: 'Aircraft sales services.', industry: 'Aviation', logo: 'B', colorIndex: 3, website: 'https://burvelaviation.com' },
    { id: 'c065', name: 'O\'Callaghan Motorcycles', description: 'Motorcycle sales services.', industry: 'Automotive', logo: 'O', colorIndex: 4, website: 'https://ocallaghanmotorcycles.com' },
    { id: 'c066', name: 'James Family Planning', description: 'Family planning financial services.', industry: 'Finance', logo: 'J', colorIndex: 5, website: 'https://jamesfamilyplanning.com' },
    { id: 'c067', name: 'Burvel Remittance', description: 'International money transfer services.', industry: 'Finance', logo: 'B', color