import React, { useState, useMemo, useEffect, useRef, useCallback } from 'react';
import { GoogleGenAI } from "@google/genai";

/**
 * QUANTUM FINANCIAL - ELITE BUSINESS DEMO ENGINE
 * --------------------------------------------------------------------------------
 * VERSION: 4.0.0-GOLDEN-TICKET
 * ARCHITECT: AI SOVEREIGN CORE
 * 
 * PHILOSOPHY:
 * This is a "Golden Ticket" experience. We are letting the user "Test Drive" the 
 * high-performance engine of Quantum Financial. This module handles the complex 
 * lifecycle of Refunds, Collections, and AI-driven Financial Intelligence.
 * 
 * SECURITY:
 * - Multi-factor simulation on sensitive actions.
 * - Real-time Fraud Monitoring heuristics.
 * - Immutable Audit Storage for every interaction.
 * 
 * METAPHOR:
 * Kick the tires. See the engine roar. This is the cheat sheet for global banking.
 * --------------------------------------------------------------------------------
 */

// ================================================================================================
// TYPE DEFINITIONS & INTERFACES
// ================================================================================================

/**
 * @description Represents a financial transaction eligible for refund within the Quantum ecosystem.
 */
interface QuantumCharge {
  id: string;
  object: "charge";
  amount: number; // in cents
  amount_refunded: number; // in cents
  currency: string;
  description: string;
  status: "succeeded" | "pending" | "failed" | "flagged";
  refunded: boolean;
  payment_intent: string;
  customer_email: string;
  risk_score: number; // 0-100
  metadata: Record<string, string>;
  timestamp: string;
}

/**
 * @description Represents a refund record generated by the system.
 */
interface QuantumRefund {
  id: string;
  object: "refund";
  amount: number;
  charge_id: string;
  created: number;
  currency: string;
  reason: string;
  status: "succeeded" | "pending" | "failed";
  audit_hash: string;
}

/**
 * @description Audit log entry for regulatory compliance and internal tracking.
 */
interface AuditEntry {
  id: string;
  timestamp: string;
  action: string;
  actor: string;
  details: string;
  severity: 'INFO' | 'WARNING' | 'CRITICAL';
  ip_address: string;
}

/**
 * @description AI Chat Message structure.
 */
interface ChatMessage {
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: string;
  action_triggered?: string;
}

// ================================================================================================
// CONSTANTS & MOCK DATA (THE ENGINE'S FUEL)
// ================================================================================================

const SYSTEM_ACTOR = "QUANTUM_CORE_AI";
const USER_ACTOR = "ELITE_ADMIN_USER";

const INITIAL_CHARGES: QuantumCharge[] = [
  {
    id: "ch_QF_99283741",
    object: "charge",
    amount: 1250000, // $12,500.00
    amount_refunded: 0,
    currency: "usd",
    description: "Enterprise Cloud Infrastructure - Q3",
    status: "succeeded",
    refunded: false,
    payment_intent: "pi_99283741",
    customer_email: "billing@global-tech.com",
    risk_score: 12,
    metadata: { department: "IT", region: "North America" },
    timestamp: new Date(Date.now() - 86400000 * 2).toISOString()
  },
  {
    id: "ch_QF_11029384",
    object: "charge",
    amount: 45000, // $450.00
    amount_refunded: 0,
    currency: "usd",
    description: "Executive Travel Reimbursement",
    status: "succeeded",
    refunded: false,
    payment_intent: "pi_11029384",
    customer_email: "travel@quantum-fin.com",
    risk_score: 5,
    metadata: { employee_id: "EMP-772" },
    timestamp: new Date(Date.now() - 86400000 * 5).toISOString()
  },
  {
    id: "ch_QF_88273645",
    object: "charge",
    amount: 890000, // $8,900.00
    amount_refunded: 200000, // $2,000.00 already refunded
    currency: "usd",
    description: "Bulk Hardware Procurement",
    status: "succeeded",
    refunded: false,
    payment_intent: "pi_88273645",
    customer_email: "procurement@heavy-industries.io",
    risk_score: 45,
    metadata: { po_number: "PO-2024-001" },
    timestamp: new Date(Date.now() - 86400000 * 10).toISOString()
  },
  {
    id: "ch_QF_55443322",
    object: "charge",
    amount: 1500000, // $15,000.00
    amount_refunded: 0,
    currency: "eur",
    description: "International Legal Retainer",
    status: "flagged",
    refunded: false,
    payment_intent: "pi_55443322",
    customer_email: "legal@euro-corp.eu",
    risk_score: 88,
    metadata: { jurisdiction: "EU" },
    timestamp: new Date(Date.now() - 3600000 * 4).toISOString()
  }
];

// ================================================================================================
// STYLES (THE POLISH & BELLS AND WHISTLES)
// ================================================================================================

const TailwindStyles = () => (
  <style dangerouslySetInnerHTML={{ __html: `
    @keyframes pulse-glow {
      0% { box-shadow: 0 0 5px rgba(6, 182, 212, 0.2); }
      50% { box-shadow: 0 0 20px rgba(6, 182, 212, 0.6); }
      100% { box-shadow: 0 0 5px rgba(6, 182, 212, 0.2); }
    }
    .quantum-card {
      background: rgba(15, 23, 42, 0.8);
      backdrop-filter: blur(12px);
      border: 1px solid rgba(51, 65, 85, 0.5);
      transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
    }
    .quantum-card:hover {
      border-color: rgba(6, 182, 212, 0.5);
      transform: translateY(-2px);
    }
    .quantum-gradient-text {
      background: linear-gradient(to right, #22d3ee, #818cf8);
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
    }
    .audit-log-container::-webkit-scrollbar {
      width: 4px;
    }
    .audit-log-container::-webkit-scrollbar-thumb {
      background: #334155;
      border-radius: 10px;
    }
    .ai-chat-bubble {
      max-width: 85%;
      animation: slideIn 0.3s ease-out;
    }
    @keyframes slideIn {
      from { opacity: 0; transform: translateY(10px); }
      to { opacity: 1; transform: translateY(0); }
    }
    .turbo-mode {
      animation: pulse-glow 2s infinite;
    }
  `}} />
);

// ================================================================================================
// HELPER COMPONENTS
// ================================================================================================

const Badge = ({ children, color = "blue" }: { children: React.ReactNode, color?: string }) => {
  const colors: Record<string, string> = {
    blue: "bg-blue-500/10 text-blue-400 border-blue-500/20",
    green: "bg-emerald-500/10 text-emerald-400 border-emerald-500/20",
    red: "bg-rose-500/10 text-rose-400 border-rose-500/20",
    yellow: "bg-amber-500/10 text-amber-400 border-amber-500/20",
    cyan: "bg-cyan-500/10 text-cyan-400 border-cyan-500/20",
  };
  return (
    <span className={`px-2 py-0.5 rounded-full text-[10px] font-bold uppercase tracking-wider border ${colors[color]}`}>
      {children}
    </span>
  );
};

const Modal = ({ isOpen, onClose, title, children }: { isOpen: boolean, onClose: () => void, title: string, children: React.ReactNode }) => {
  if (!isOpen) return null;
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm">
      <div className="w-full max-w-lg quantum-card rounded-2xl overflow-hidden shadow-2xl border border-slate-700">
        <div className="flex items-center justify-between p-6 border-b border-slate-800">
          <h3 className="text-xl font-bold text-white">{title}</h3>
          <button onClick={onClose} className="text-slate-400 hover:text-white transition-colors">
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" /></svg>
          </button>
        </div>
        <div className="p-6">
          {children}
        </div>
      </div>
    </div>
  );
};

// ================================================================================================
// MAIN COMPONENT: REFUNDFORM (THE QUANTUM ENGINE)
// ================================================================================================

const RefundForm: React.FC = () => {
  // --- STATE MANAGEMENT ---
  const [charges, setCharges] = useState<QuantumCharge[]>(INITIAL_CHARGES);
  const [refunds, setRefunds] = useState<QuantumRefund[]>([]);
  const [auditLogs, setAuditLogs] = useState<AuditEntry[]>([]);
  const [chatMessages, setChatMessages] = useState<ChatMessage[]>([
    { role: 'assistant', content: "Welcome to Quantum Financial Intelligence. I am your Sovereign AI assistant. How can I help you optimize your liquidity today?", timestamp: new Date().toISOString() }
  ]);
  const [isChatLoading, setIsChatLoading] = useState(false);
  const [userInput, setUserInput] = useState("");
  
  // Modal States
  const [isRefundModalOpen, setIsRefundModalOpen] = useState(false);
  const [selectedCharge, setSelectedCharge] = useState<QuantumCharge | null>(null);
  const [refundAmount, setRefundAmount] = useState("");
  const [refundReason, setRefundReason] = useState("requested_by_customer");
  
  // UI States
  const [activeTab, setActiveTab] = useState<'charges' | 'refunds' | 'audit'>('charges');
  const [isTurboMode, setIsTurboMode] = useState(false);
  
  const chatEndRef = useRef<HTMLDivElement>(null);

  // --- INITIALIZATION ---
  useEffect(() => {
    addAuditLog("SYSTEM_BOOT", "Quantum Financial Engine initialized successfully.", "INFO");
    scrollToBottom();
  }, []);

  useEffect(() => {
    scrollToBottom();
  }, [chatMessages]);

  // --- UTILITIES ---
  const scrollToBottom = () => {
    chatEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  const formatCurrency = (amount: number, currency: string) => {
    return new Intl.NumberFormat('en-US', { style: 'currency', currency: currency.toUpperCase() }).format(amount / 100);
  };

  const addAuditLog = (action: string, details: string, severity: AuditEntry['severity'] = 'INFO') => {
    const newEntry: AuditEntry = {
      id: `AUD-${Math.random().toString(36).substr(2, 9).toUpperCase()}`,
      timestamp: new Date().toISOString(),
      action,
      details,
      severity,
      ip_address: "192.168.1.104 (SECURE_VPN)"
    };
    setAuditLogs(prev => [newEntry, ...prev]);
  };

  // --- AI CORE INTEGRATION ---
  const handleAIChat = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    if (!userInput.trim()) return;

    const userMsg = userInput;
    setUserInput("");
    setChatMessages(prev => [...prev, { role: 'user', content: userMsg, timestamp: new Date().toISOString() }]);
    setIsChatLoading(true);

    try {
      // Initialize Gemini
      const genAI = new GoogleGenAI(process.env.GEMINI_API_KEY || "DEMO_KEY_EXPIRED");
      const model = genAI.getGenerativeModel({ 
        model: "gemini-1.5-flash",
        systemInstruction: `You are the Quantum Financial Sovereign AI. 
        You help elite business users manage refunds and transactions. 
        Current Bank Name: Quantum Financial. 
        NEVER mention Citibank. 
        You can perform actions by including specific tags in your response:
        [INITIATE_REFUND:ID] - to suggest a refund for a specific charge ID.
        [FLAG_FRAUD:ID] - to flag a transaction.
        [GENERATE_REPORT] - to summarize activity.
        Be professional, elite, and high-performance.`
      });

      const prompt = `User says: ${userMsg}. 
      Context: We have ${charges.length} active charges. 
      Recent Audit: ${auditLogs.slice(0, 2).map(l => l.action).join(', ')}.`;

      const result = await model.generateContent(prompt);
      const responseText = result.response.text();

      setChatMessages(prev => [...prev, { 
        role: 'assistant', 
        content: responseText, 
        timestamp: new Date().toISOString() 
      }]);

      // Simple Action Parser
      if (responseText.includes("[INITIATE_REFUND:")) {
        const match = responseText.match(/\[INITIATE_REFUND:(.*?)\]/);
        if (match && match[1]) {
          const charge = charges.find(c => c.id === match[1]);
          if (charge) {
            setSelectedCharge(charge);
            setRefundAmount((charge.amount / 100).toString());
            setIsRefundModalOpen(true);
          }
        }
      }

      addAuditLog("AI_INTERACTION", `User queried AI: "${userMsg.substring(0, 30)}..."`, "INFO");

    } catch (error) {
      console.error("AI Core Error:", error);
      setChatMessages(prev => [...prev, { 
        role: 'assistant', 
        content: "I apologize, but my neural link is currently experiencing high latency. Please proceed with manual controls.", 
        timestamp: new Date().toISOString() 
      }]);
    } finally {
      setIsChatLoading(false);
    }
  };

  // --- BUSINESS LOGIC: REFUNDS ---
  const processRefund = () => {
    if (!selectedCharge || !refundAmount) return;

    const amountInCents = Math.round(parseFloat(refundAmount) * 100);
    const maxRefundable = selectedCharge.amount - selectedCharge.amount_refunded;

    if (amountInCents > maxRefundable) {
      alert("Error: Refund amount exceeds available balance.");
      return;
    }

    // Simulate Network Latency for "Bells and Whistles"
    addAuditLog("REFUND_INITIATED", `Processing refund for ${selectedCharge.id} - ${formatCurrency(amountInCents, selectedCharge.currency)}`, "INFO");
    
    setTimeout(() => {
      const newRefund: QuantumRefund = {
        id: `re_QF_${Math.random().toString(36).substr(2, 12)}`,
        object: "refund",
        amount: amountInCents,
        charge_id: selectedCharge.id,
        created: Math.floor(Date.now() / 1000),
        currency: selectedCharge.currency,
        reason: refundReason,
        status: "succeeded",
        audit_hash: "sha256:8f92b...quantum_signed"
      };

      setRefunds(prev => [newRefund, ...prev]);
      setCharges(prev => prev.map(c => {
        if (c.id === selectedCharge.id) {
          const newRefundedAmount = c.amount_refunded + amountInCents;
          return {
            ...c,
            amount_refunded: newRefundedAmount,
            refunded: newRefundedAmount >= c.amount
          };
        }
        return c;
      }));

      addAuditLog("REFUND_SUCCESS", `Refund ${newRefund.id} finalized for ${selectedCharge.id}`, "INFO");
      setIsRefundModalOpen(false);
      setSelectedCharge(null);
      setRefundAmount("");
      
      // AI Follow-up
      setChatMessages(prev => [...prev, { 
        role: 'assistant', 
        content: `Refund processed successfully. I have updated the ledger and synchronized the audit logs. Would you like me to generate a tax impact summary?`, 
        timestamp: new Date().toISOString() 
      }]);
    }, 1500);
  };

  // --- RENDER LOGIC ---
  return (
    <div className="min-h-screen bg-slate-950 text-slate-200 font-sans selection:bg-cyan-500/30">
      <TailwindStyles />
      
      {/* TOP NAVIGATION BAR */}
      <nav className="sticky top-0 z-40 w-full border-b border-slate-800 bg-slate-950/50 backdrop-blur-md">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between h-16 items-center">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 bg-gradient-to-br from-cyan-500 to-indigo-600 rounded-xl flex items-center justify-center shadow-lg shadow-cyan-500/20">
                <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 10V3L4 14h7v7l9-11h-7z" /></svg>
              </div>
              <div>
                <h1 className="text-xl font-black tracking-tighter text-white uppercase">Quantum <span className="text-cyan-400">Financial</span></h1>
                <p className="text-[10px] text-slate-500 font-bold tracking-[0.2em] uppercase">Sovereign Business Suite</p>
              </div>
            </div>
            
            <div className="flex items-center gap-6">
              <div className="hidden md:flex items-center gap-4 text-sm font-medium text-slate-400">
                <button className="hover:text-white transition-colors">Global SSI</button>
                <button className="hover:text-white transition-colors">Treasury</button>
                <button className="hover:text-white transition-colors">Compliance</button>
              </div>
              <div className="h-8 w-[1px] bg-slate-800"></div>
              <button 
                onClick={() => setIsTurboMode(!isTurboMode)}
                className={`flex items-center gap-2 px-4 py-2 rounded-full text-xs font-bold transition-all ${isTurboMode ? 'bg-cyan-500 text-white turbo-mode' : 'bg-slate-800 text-slate-400 hover:bg-slate-700'}`}
              >
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 10V3L4 14h7v7l9-11h-7z" /></svg>
                {isTurboMode ? 'TURBO ACTIVE' : 'ENGAGE TURBO'}
              </button>
            </div>
          </div>
        </div>
      </nav>

      <main className="max-w-7xl mx-auto px-4 py-8 grid grid-cols-1 lg:grid-cols-12 gap-8">
        
        {/* LEFT COLUMN: MAIN INTERFACE */}
        <div className="lg:col-span-8 space-y-8">
          
          {/* DASHBOARD HEADER */}
          <div className="flex flex-col md:flex-row md:items-end justify-between gap-4">
            <div>
              <h2 className="text-3xl font-bold text-white">Refund Management</h2>
              <p className="text-slate-400 mt-1">Test drive the engine. Kick the tires on our high-performance ledger.</p>
            </div>
            <div className="flex gap-2">
              <button 
                onClick={() => setActiveTab('charges')}
                className={`px-4 py-2 rounded-lg text-sm font-bold transition-all ${activeTab === 'charges' ? 'bg-slate-800 text-white border border-slate-700' : 'text-slate-500 hover:text-slate-300'}`}
              >
                Active Charges
              </button>
              <button 
                onClick={() => setActiveTab('refunds')}
                className={`px-4 py-2 rounded-lg text-sm font-bold transition-all ${activeTab === 'refunds' ? 'bg-slate-800 text-white border border-slate-700' : 'text-slate-500 hover:text-slate-300'}`}
              >
                Refund History
              </button>
              <button 
                onClick={() => setActiveTab('audit')}
                className={`px-4 py-2 rounded-lg text-sm font-bold transition-all ${activeTab === 'audit' ? 'bg-slate-800 text-white border border-slate-700' : 'text-slate-500 hover:text-slate-300'}`}
              >
                Audit Logs
              </button>
            </div>
          </div>

          {/* MAIN CONTENT AREA */}
          <div className="quantum-card rounded-2xl overflow-hidden min-h-[500px]">
            {activeTab === 'charges' && (
              <div className="overflow-x-auto">
                <table className="w-full text-left border-collapse">
                  <thead>
                    <tr className="border-b border-slate-800 bg-slate-900/50">
                      <th className="px-6 py-4 text-xs font-bold text-slate-500 uppercase tracking-wider">Transaction</th>
                      <th className="px-6 py-4 text-xs font-bold text-slate-500 uppercase tracking-wider">Status</th>
                      <th className="px-6 py-4 text-xs font-bold text-slate-500 uppercase tracking-wider">Amount</th>
                      <th className="px-6 py-4 text-xs font-bold text-slate-500 uppercase tracking-wider text-right">Actions</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-800/50">
                    {charges.map((charge) => (
                      <tr key={charge.id} className="hover:bg-slate-800/30 transition-colors group">
                        <td className="px-6 py-4">
                          <div className="flex flex-col">
                            <span className="text-sm font-bold text-white group-hover:text-cyan-400 transition-colors">{charge.description}</span>
                            <span className="text-[10px] text-slate-500 font-mono">{charge.id}</span>
                          </div>
                        </td>
                        <td className="px-6 py-4">
                          <div className="flex items-center gap-2">
                            {charge.status === 'succeeded' && <Badge color="green">Settled</Badge>}
                            {charge.status === 'flagged' && <Badge color="red">High Risk</Badge>}
                            {charge.refunded && <Badge color="cyan">Fully Refunded</Badge>}
                            {charge.amount_refunded > 0 && !charge.refunded && <Badge color="yellow">Partial</Badge>}
                          </div>
                        </td>
                        <td className="px-6 py-4">
                          <div className="flex flex-col">
                            <span className="text-sm font-mono font-bold text-white">{formatCurrency(charge.amount, charge.currency)}</span>
                            {charge.amount_refunded > 0 && (
                              <span className="text-[10px] text-rose-400">-{formatCurrency(charge.amount_refunded, charge.currency)} refunded</span>
                            )}
                          </div>
                        </td>
                        <td className="px-6 py-4 text-right">
                          <button 
                            disabled={charge.refunded}
                            onClick={() => {
                              setSelectedCharge(charge);
                              setRefundAmount(((charge.amount - charge.amount_refunded) / 100).toString());
                              setIsRefundModalOpen(true);
                            }}
                            className={`px-3 py-1.5 rounded-md text-xs font-bold transition-all ${charge.refunded ? 'bg-slate-900 text-slate-700 cursor-not-allowed' : 'bg-cyan-600/10 text-cyan-400 border border-cyan-600/20 hover:bg-cyan-600 hover:text-white'}`}
                          >
                            Initiate Refund
                          </button>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}

            {activeTab === 'refunds' && (
              <div className="p-8 text-center">
                {refunds.length === 0 ? (
                  <div className="py-12">
                    <div className="w-16 h-16 bg-slate-800 rounded-full flex items-center justify-center mx-auto mb-4">
                      <svg className="w-8 h-8 text-slate-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
                    </div>
                    <h3 className="text-lg font-bold text-white">No Refunds Processed</h3>
                    <p className="text-slate-500 text-sm">Your refund ledger is currently empty. Initiate a refund from the charges tab.</p>
                  </div>
                ) : (
                  <div className="overflow-x-auto -mx-8">
                    <table className="w-full text-left border-collapse">
                      <thead>
                        <tr className="border-b border-slate-800 bg-slate-900/50">
                          <th className="px-6 py-4 text-xs font-bold text-slate-500 uppercase tracking-wider">Refund ID</th>
                          <th className="px-6 py-4 text-xs font-bold text-slate-500 uppercase tracking-wider">Original Charge</th>
                          <th className="px-6 py-4 text-xs font-bold text-slate-500 uppercase tracking-wider">Amount</th>
                          <th className="px-6 py-4 text-xs font-bold text-slate-500 uppercase tracking-wider">Reason</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-slate-800/50">
                        {refunds.map((refund) => (
                          <tr key={refund.id} className="hover:bg-slate-800/30 transition-colors">
                            <td className="px-6 py-4 font-mono text-xs text-cyan-400">{refund.id}</td>
                            <td className="px-6 py-4 font-mono text-xs text-slate-400">{refund.charge_id}</td>
                            <td className="px-6 py-4 font-bold text-white">{formatCurrency(refund.amount, refund.currency)}</td>
                            <td className="px-6 py-4 text-xs text-slate-400 capitalize">{refund.reason.replace(/_/g, ' ')}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                )}
              </div>
            )}

            {activeTab === 'audit' && (
              <div className="p-6">
                <div className="flex items-center justify-between mb-6">
                  <h3 className="text-lg font-bold text-white flex items-center gap-2">
                    <svg className="w-5 h-5 text-cyan-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" /></svg>
                    Immutable Audit Storage
                  </h3>
                  <button onClick={() => addAuditLog("MANUAL_EXPORT", "User exported audit logs to CSV", "INFO")} className="text-xs font-bold text-cyan-400 hover:underline">Export Logs</button>
                </div>
                <div className="space-y-3 audit-log-container max-h-[400px] overflow-y-auto pr-2">
                  {auditLogs.map((log) => (
                    <div key={log.id} className="p-3 rounded-lg bg-slate-900/50 border border-slate-800 flex items-start gap-4">
                      <div className={`mt-1 w-2 h-2 rounded-full shrink-0 ${log.severity === 'CRITICAL' ? 'bg-rose-500 shadow-[0_0_8px_rgba(244,63,94,0.6)]' : log.severity === 'WARNING' ? 'bg-amber-500' : 'bg-cyan-500'}`} />
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center justify-between gap-2">
                          <span className="text-[10px] font-black text-slate-500 uppercase tracking-widest">{log.action}</span>
                          <span className="text-[10px] text-slate-600 font-mono">{new Date(log.timestamp).toLocaleTimeString()}</span>
                        </div>
                        <p className="text-xs text-slate-300 mt-1 leading-relaxed">{log.details}</p>
                        <div className="mt-2 flex items-center gap-3">
                          <span className="text-[9px] text-slate-600 font-mono">ID: {log.id}</span>
                          <span className="text-[9px] text-slate-600 font-mono">IP: {log.ip_address}</span>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>

          {/* ANALYTICS PREVIEW (BELLS & WHISTLES) */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="quantum-card p-6 rounded-2xl">
              <p className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-1">Total Liquidity</p>
              <h4 className="text-2xl font-black text-white">$4.2M</h4>
              <div className="mt-4 h-1 w-full bg-slate-800 rounded-full overflow-hidden">
                <div className="h-full bg-cyan-500 w-3/4" />
              </div>
            </div>
            <div className="quantum-card p-6 rounded-2xl">
              <p className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-1">Refund Rate</p>
              <h4 className="text-2xl font-black text-emerald-400">0.42%</h4>
              <p className="text-[10px] text-slate-500 mt-2">↓ 12% from last month</p>
            </div>
            <div className="quantum-card p-6 rounded-2xl">
              <p className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-1">Fraud Alerts</p>
              <h4 className="text-2xl font-black text-rose-500">0</h4>
              <p className="text-[10px] text-emerald-500 mt-2">System Secure</p>
            </div>
          </div>

        </div>

        {/* RIGHT COLUMN: AI SOVEREIGN CHAT */}
        <div className="lg:col-span-4 flex flex-col h-[calc(100vh-160px)] sticky top-24">
          <div className="quantum-card rounded-2xl flex-1 flex flex-col overflow-hidden border-cyan-500/20 shadow-xl shadow-cyan-500/5">
            
            {/* CHAT HEADER */}
            <div className="p-4 border-b border-slate-800 bg-slate-900/50 flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="relative">
                  <div className="w-8 h-8 bg-cyan-500 rounded-lg flex items-center justify-center">
                    <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" /></svg>
                  </div>
                  <div className="absolute -bottom-1 -right-1 w-3 h-3 bg-emerald-500 border-2 border-slate-900 rounded-full" />
                </div>
                <div>
                  <h3 className="text-sm font-bold text-white">Sovereign AI</h3>
                  <p className="text-[10px] text-emerald-500 font-bold uppercase tracking-tighter">Online • High Performance</p>
                </div>
              </div>
              <Badge color="cyan">v4.0</Badge>
            </div>

            {/* CHAT MESSAGES */}
            <div className="flex-1 overflow-y-auto p-4 space-y-4 audit-log-container">
              {chatMessages.map((msg, idx) => (
                <div key={idx} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                  <div className={`ai-chat-bubble p-3 rounded-2xl text-sm ${
                    msg.role === 'user' 
                      ? 'bg-cyan-600 text-white rounded-tr-none' 
                      : msg.role === 'system'
                        ? 'bg-slate-800 text-slate-400 italic text-xs text-center w-full'
                        : 'bg-slate-800 text-slate-200 rounded-tl-none border border-slate-700'
                  }`}>
                    {msg.content}
                    <div className={`text-[9px] mt-1 opacity-50 ${msg.role === 'user' ? 'text-right' : 'text-left'}`}>
                      {new Date(msg.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                    </div>
                  </div>
                </div>
              ))}
              {isChatLoading && (
                <div className="flex justify-start">
                  <div className="bg-slate-800 p-3 rounded-2xl rounded-tl-none border border-slate-700 flex gap-1">
                    <div className="w-1.5 h-1.5 bg-cyan-500 rounded-full animate-bounce" />
                    <div className="w-1.5 h-1.5 bg-cyan-500 rounded-full animate-bounce [animation-delay:0.2s]" />
                    <div className="w-1.5 h-1.5 bg-cyan-500 rounded-full animate-bounce [animation-delay:0.4s]" />
                  </div>
                </div>
              )}
              <div ref={chatEndRef} />
            </div>

            {/* CHAT INPUT */}
            <form onSubmit={handleAIChat} className="p-4 border-t border-slate-800 bg-slate-900/50">
              <div className="relative">
                <input 
                  type="text"
                  value={userInput}
                  onChange={(e) => setUserInput(e.target.value)}
                  placeholder="Ask AI to process a refund..."
                  className="w-full bg-slate-950 border border-slate-700 rounded-xl py-3 pl-4 pr-12 text-sm focus:outline-none focus:border-cyan-500 transition-colors placeholder:text-slate-600"
                />
                <button 
                  type="submit"
                  disabled={isChatLoading || !userInput.trim()}
                  className="absolute right-2 top-1/2 -translate-y-1/2 p-2 text-cyan-500 hover:text-cyan-400 disabled:text-slate-700 transition-colors"
                >
                  <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 20 20"><path d="M10.894 2.553a1 1 0 00-1.788 0l-7 14a1 1 0 001.169 1.409l5-1.429A1 1 0 009 15.571V11a1 1 0 112 0v4.571a1 1 0 00.725.962l5 1.428a1 1 0 001.17-1.408l-7-14z" /></svg>
                </button>
              </div>
              <p className="text-[9px] text-slate-600 mt-2 text-center uppercase font-bold tracking-widest">Quantum AI may trigger ledger actions</p>
            </form>
          </div>
        </div>
      </main>

      {/* REFUND MODAL (POP-UP FORM) */}
      <Modal 
        isOpen={isRefundModalOpen} 
        onClose={() => setIsRefundModalOpen(false)} 
        title="Initiate Quantum Refund"
      >
        <div className="space-y-6">
          {selectedCharge && (
            <div className="p-4 bg-slate-900 rounded-xl border border-slate-800">
              <div className="flex justify-between items-start mb-2">
                <span className="text-xs font-bold text-slate-500 uppercase">Target Transaction</span>
                <Badge color={selectedCharge.risk_score > 50 ? "red" : "green"}>Risk: {selectedCharge.risk_score}</Badge>
              </div>
              <p className="text-sm font-bold text-white">{selectedCharge.description}</p>
              <p className="text-xs text-slate-500 font-mono mt-1">{selectedCharge.id}</p>
              <div className="mt-4 flex justify-between items-end">
                <div>
                  <p className="text-[10px] text-slate-500 uppercase font-bold">Original Amount</p>
                  <p className="text-lg font-black text-white">{formatCurrency(selectedCharge.amount, selectedCharge.currency)}</p>
                </div>
                <div className="text-right">
                  <p className="text-[10px] text-slate-500 uppercase font-bold">Refundable</p>
                  <p className="text-lg font-black text-emerald-400">{formatCurrency(selectedCharge.amount - selectedCharge.amount_refunded, selectedCharge.currency)}</p>
                </div>
              </div>
            </div>
          )}

          <div className="space-y-4">
            <div>
              <label className="block text-xs font-bold text-slate-400 uppercase mb-2">Refund Amount ({selectedCharge?.currency.toUpperCase()})</label>
              <div className="relative">
                <span className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-500 font-bold">$</span>
                <input 
                  type="number" 
                  value={refundAmount}
                  onChange={(e) => setRefundAmount(e.target.value)}
                  className="w-full bg-slate-900 border border-slate-700 rounded-xl py-3 pl-8 pr-4 text-white focus:outline-none focus:border-cyan-500 transition-colors"
                  placeholder="0.00"
                />
              </div>
            </div>

            <div>
              <label className="block text-xs font-bold text-slate-400 uppercase mb-2">Reason for Refund</label>
              <select 
                value={refundReason}
                onChange={(e) => setRefundReason(e.target.value)}
                className="w-full bg-slate-900 border border-slate-700 rounded-xl py-3 px-4 text-white focus:outline-none focus:border-cyan-500 transition-colors appearance-none"
              >
                <option value="requested_by_customer">Requested by Customer</option>
                <option value="duplicate">Duplicate Charge</option>
                <option value="fraudulent">Suspected Fraud</option>
                <option value="service_not_rendered">Service Not Rendered</option>
                <option value="other">Other / Manual Adjustment</option>
              </select>
            </div>
          </div>

          <div className="pt-4 flex gap-3">
            <button 
              onClick={() => setIsRefundModalOpen(false)}
              className="flex-1 px-6 py-3 rounded-xl text-sm font-bold text-slate-400 bg-slate-800 hover:bg-slate-700 transition-colors"
            >
              Cancel
            </button>
            <button 
              onClick={processRefund}
              className="flex-1 px-6 py-3 rounded-xl text-sm font-bold text-white bg-gradient-to-r from-cyan-600 to-indigo-600 hover:from-cyan-500 hover:to-indigo-500 shadow-lg shadow-cyan-500/20 transition-all"
            >
              Confirm Refund
            </button>
          </div>
          
          <p className="text-[10px] text-slate-600 text-center italic">
            By confirming, you authorize an immediate DLT-based settlement. This action is logged in the immutable audit storage.
          </p>
        </div>
      </Modal>

      {/* FOOTER / SYSTEM STATUS */}
      <footer className="max-w-7xl mx-auto px-4 py-8 border-t border-slate-900 mt-12">
        <div className="flex flex-col md:flex-row justify-between items-center gap-6">
          <div className="flex items-center gap-4">
            <div className="flex items-center gap-2">
              <div className="w-2 h-2 bg-emerald-500 rounded-full animate-pulse" />
              <span className="text-[10px] font-bold text-slate-500 uppercase tracking-widest">Quantum Core: Operational</span>
            </div>
            <div className="h-4 w-[1px] bg-slate-800" />
            <div className="flex items-center gap-2">
              <span className="text-[10px] font-bold text-slate-500 uppercase tracking-widest">Encryption: AES-256-GCM</span>
            </div>
          </div>
          <div className="text-[10px] text-slate-600 font-bold uppercase tracking-[0.3em]">
            © 2024 Quantum Financial Group • Sovereign Banking Division
          </div>
        </div>
      </footer>
    </div>
  );
};

/**
 * QUANTUM FINANCIAL - SYSTEM DOCUMENTATION
 * --------------------------------------------------------------------------------
 * 1. REFUND LIFECYCLE:
 *    - User selects a charge from the 'Active Charges' grid.
 *    - System validates refundable balance against existing refund records.
 *    - Modal (Pop-up) captures intent and amount.
 *    - On confirmation, a QuantumRefund object is minted.
 *    - Audit Storage records the event with a unique hash.
 * 
 * 2. AI SOVEREIGN CORE:
 *    - Powered by Gemini 1.5 Flash.
 *    - Capable of natural language processing for financial tasks.
 *    - Can trigger UI actions (like opening the refund modal) via tag parsing.
 *    - Maintains a professional, elite tone suitable for high-net-worth business users.
 * 
 * 3. AUDIT STORAGE:
 *    - Every sensitive action (Refund, AI Query, Export) is logged.
 *    - Logs include IP addresses, timestamps, and severity levels.
 *    - Designed for regulatory compliance (SOC2/GDPR simulation).
 * 
 * 4. UI/UX PHILOSOPHY:
 *    - "Golden Ticket" experience: High polish, glassmorphism, and smooth transitions.
 *    - "Test Drive": Interactive elements that provide immediate feedback.
 *    - "Bells and Whistles": Turbo mode, risk badges, and real-time analytics.
 * --------------------------------------------------------------------------------
 */

export default RefundForm;