// components/views/personal/InvestmentsView.tsx
import React, { useContext, useState, useMemo } from 'react';
import { DataContext } from '../../../context/DataContext';
import Card from '../../Card';
import type { Asset } from '../../../types';
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip, AreaChart, Area } from 'recharts';
import InvestmentPortfolio from '../../InvestmentPortfolio';

// ================================================================================================
// HELPER & SUB-COMPONENTS
// ================================================================================================

const ESGScore: React.FC<{ rating: number }> = ({ rating }) => (
    <div className="flex items-center" aria-label={`ESG rating: ${rating} out of 5`}>
        {Array.from({ length: 5 }).map((_, i) => (
            <svg
                key={i}
                xmlns="http://www.w3.org/2000/svg"
                className={`h-5 w-5 ${i < rating ? 'text-green-400' : 'text-gray-600'}`}
                fill="currentColor"
                viewBox="0 0 20 20"
                aria-hidden="true"
            >
                <path d="M10 15a.75.75 0 01-.75-.75V7.612L7.22 9.63a.75.75 0 01-1.06-1.06l3.25-3.25a.75.75 0 011.18 0l3.25 3.25a.75.75 0 11-1.06 1.06L10.75 7.612v6.638A.75.75 0 0110 15z" />
            </svg>
        ))}
    </div>
);

const InvestmentModal: React.FC<{
    asset: Asset | null;
    onClose: () => void;
    onInvest: (assetName: string, amount: number) => void;
}> = ({ asset, onClose, onInvest }) => {
    const [amount, setAmount] = useState('1000');

    if (!asset) return null;

    const handleInvestClick = () => {
        onInvest(asset.name, parseFloat(amount));
        onClose();
    };

    return (
        <div className="fixed inset-0 bg-black/70 flex items-center justify-center z-50 backdrop-blur-sm" onClick={onClose}>
            <div className="bg-gray-800 rounded-lg shadow-2xl max-w-md w-full border border-gray-700" onClick={e => e.stopPropagation()}>
                <div className="p-4 border-b border-gray-700">
                    <h3 className="text-lg font-semibold text-white">Invest in {asset.name}</h3>
                </div>
                <div className="p-6 space-y-4">
                    <p className="text-sm text-gray-400">{asset.description}</p>
                    <div>
                        <label className="block text-sm font-medium text-gray-300">Amount (USD)</label>
                        <input
                            type="number"
                            value={amount}
                            onChange={e => setAmount(e.target.value)}
                            className="mt-1 w-full bg-gray-700/50 border-gray-600 rounded-md p-2 text-white"
                        />
                    </div>
                    <button onClick={handleInvestClick} className="w-full py-2 bg-cyan-600 hover:bg-cyan-700 text-white rounded-lg">
                        Confirm Investment
                    </button>
                </div>
            </div>
        </div>
    );
};


// ================================================================================================
// MAIN VIEW COMPONENT: InvestmentsView (CapitalVista)
// ================================================================================================

const InvestmentsView: React.FC = () => {
    const context = useContext(DataContext);
    const [monthlyContribution, setMonthlyContribution] = useState(500);
    const [selectedImpactAsset, setSelectedImpactAsset] = useState<Asset | null>(null);

    if (!context) {
        throw new Error("InvestmentsView must be within a DataProvider.");
    }

    const { assets, impactInvestments, addTransaction } = context;

    const totalValue = useMemo(() => assets.reduce((sum, asset) => sum + asset.value, 0), [assets]);

    const projectionData = useMemo(() => {
        let futureValue = totalValue;
        const data = [{ year: 'Now', value: futureValue }];
        for (let i = 1; i <= 10; i++) {
            futureValue = (futureValue + monthlyContribution * 12) * 1.07; // 7% annual growth
            data.push({ year: `Year ${i}`, value: futureValue });
        }
        return data;
    }, [totalValue, monthlyContribution]);

    const handleInvest = (assetName: string, amount: number) => {
// FIX: The `addTransaction` function expects an object of type `Omit<Transaction, 'id'>`.
// The `id` property is generated by the backend and should not be sent in the request.
        addTransaction({
            type: 'expense',
            category: 'Investments',
            description: `Invest in ${assetName}`,
            amount: amount,
            date: new Date().toISOString().split('T')[0],
        });
        alert(`Successfully invested $${amount} in ${assetName}. See the new transaction in your history.`);
    };

    return (
        <>
            <div className="space-y-6">
                <h2 className="text-3xl font-bold text-white tracking-wider">Investments (CapitalVista)</h2>

                <InvestmentPortfolio />

                <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                    <Card title="Asset Performance (YTD)">
                        <div className="h-80">
                            <ResponsiveContainer width="100%" height="100%">
                                <BarChart data={assets} layout="vertical" margin={{ top: 5, right: 30, left: 20, bottom: 5 }}>
                                    <XAxis type="number" stroke="#9ca3af" domain={[0, 50]} unit="%" />
                                    <YAxis type="category" dataKey="name" stroke="#9ca3af" width={80} />
                                    <Tooltip contentStyle={{ backgroundColor: 'rgba(31, 41, 55, 0.8)', borderColor: '#4b5563' }} />
                                    <Bar dataKey="performanceYTD" name="YTD Performance" fill="#06b6d4" radius={[0, 4, 4, 0]} />
                                </BarChart>
                            </ResponsiveContainer>
                        </div>
                    </Card>

                    <Card title="AI Growth Simulator">
                        <div className="mb-4">
                            <label className="block text-sm text-gray-300">Monthly Contribution: <span className="font-bold text-white">${monthlyContribution.toLocaleString()}</span></label>
                            <input
                                type="range"
                                min="0"
                                max="2000"
                                step="50"
                                value={monthlyContribution}
                                onChange={e => setMonthlyContribution(Number(e.target.value))}
                                className="w-full h-2 bg-gray-700 rounded-lg appearance-none cursor-pointer"
                                aria-label="Monthly investment contribution"
                            />
                        </div>
                        <div className="h-64">
                            <ResponsiveContainer width="100%" height="100%">
                                <AreaChart data={projectionData}>
                                    <defs><linearGradient id="colorGrowth" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#06b6d4" stopOpacity={0.8}/><stop offset="95%" stopColor="#06b6d4" stopOpacity={0}/></linearGradient></defs>
                                    <XAxis dataKey="year" stroke="#9ca3af" />
                                    <YAxis stroke="#9ca3af" tickFormatter={(tick) => `$${(tick / 1000).toFixed(0)}k`} />
                                    <Tooltip contentStyle={{ backgroundColor: 'rgba(31, 41, 55, 0.8)', borderColor: '#4b5563' }} formatter={(value: number) => [`$${value.toLocaleString(undefined, {maximumFractionDigits: 0})}`, "Projected Value"]} />
                                    <Area type="monotone" dataKey="value" stroke="#06b6d4" fill="url(#colorGrowth)" />
                                </AreaChart>
                            </ResponsiveContainer>
                        </div>
                    </Card>
                </div>
                
                {/* Social Impact Investing Section */}
                <Card title="Social Impact Investing (ESG)">
                    <p className="text-sm text-gray-400 mb-4">Invest in companies that align with your values. All options below are highly rated for their Environmental, Social, and Governance practices.</p>
                    <div className="space-y-4">
                        {impactInvestments.map(asset => (
                            <div key={asset.name} className="p-4 bg-gray-800/50 rounded-lg flex flex-col sm:flex-row justify-between items-center gap-4">
                                <div className="flex-grow">
                                    <div className="flex items-center gap-4">
                                        <ESGScore rating={asset.esgRating || 0} />
                                        <h4 className="font-semibold text-white">{asset.name}</h4>
                                    </div>
                                    <p className="text-sm text-gray-400 mt-2">{asset.description}</p>
                                </div>
                                <button onClick={() => setSelectedImpactAsset(asset)} className="w-full sm:w-auto text-sm px-4 py-2 bg-cyan-600/50 hover:bg-cyan-600 text-white rounded-lg transition-colors flex-shrink-0">
                                    Invest Now
                                </button>
                            </div>
                        ))}
                    </div>
                </Card>
            </div>
            <InvestmentModal
                asset={selectedImpactAsset}
                onClose={() => setSelectedImpactAsset(null)}
                onInvest={handleInvest}
            />
        </>
    );
};

export default InvestmentsView;